# --- Theme Settings ---
remote_theme: "mmistakes/minimal-mistakes"  
minimal_mistakes_skin: "default"

# --- Site Settings ---
locale: "ko-KR" # ğŸ”¥ í•œêµ­ì–´ ì‚¬ì´íŠ¸ë¼ë©´ ìˆ˜ì • ê¶Œì¥
title: "ê·œí˜•ì˜ ê¸°ìˆ  ë¸”ë¡œê·¸"  
name: "ê·œí˜•"                 
description: "ê°œë°œì ê³µë¶€ ê¸°ë¡ ë¸”ë¡œê·¸" 

url: "https://rbgud7957.github.io"   
baseurl: ""                          

repository: "rbgud7957/rbgud7957.github.io"  

# --- Author ---
author:
  name: "ê·œí˜•"
  avatar: "/assets/images/profile.jpg" # ì—†ìœ¼ë©´ ì§€ì›Œë„ ë¨
  bio: "ë°±ì—”ë“œ ê°œë°œì„ ê³µë¶€í•˜ë©° ê¸°ë¡í•˜ëŠ” ê¸°ìˆ  ë¸”ë¡œê·¸"
  location: "Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rbgud7957"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

paginate: 5
paginate_path: /page:num/

markdown: kramdown
highlighter: rouge

# Posts ê¸°ë³¸ ì„¤ì •
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true


include: []
exclude:
  - vendor
  - node_modules
  - "*.gemspec"
  - Gemfile
  - Gemfile.lock
  - README*
  - docs
  - _test
  - test
  - spec
  - example
  - examples

